### ISSUE TITLE
Add readme document

### ISSUE THREAD

**Issue by FuncGuy** [swathisprasad/read-replica-with-spring-boot#1]
Hi Swathi,

It would be helpful if you add the context of the project so it is easy to understand.

Thanks.

**Comment by swathisprasad** [comment]
Hi @FuncGuy,

I added a short notes. If you are interested to read further on read replicas, refer this documentation: https://blog.timescale.com/blog/scalable-postgresql-high-availability-read-scalability-streaming-replication-fb95023e2af/.
